# default minecraft's death messages
BLOCK_EXPLOSION: '§6[victim]§7 à explosé'
CONTACT: '§6[victim]§7 s''est piqué'
CRAMING: '§6[victim]§7 s''est fais piétiné'
CUSTOM: '§6[victim]§7 est mort sans explications'
DRAGON_BREATH: '§6[victim]§7 à respiré le souffle du dragon'
DROWNING: '§6[victim]§7 n''est noyé dans l''eau'
DRYOUT: '§6[victim]§7 a suffoqué hors de l''eau'
ENTITY_ATTACK: '§6[victim]§7 à été tué'
ENTITY_EXPLOSION: '§6[victim]§7 a explosé'
ENTITY_SWEEP_ATTACK: '§6[victim]§7 s''est pris un bout d''épée'
FALL: '§6[victim]§7 est tombé de §8[fall_dist]§7 blocs'
FALLING_BLOCK: '§6[victim]§7 s''est fais écrasé'
FIRE: '§6[victim]§7 à brulé'
FIRE_TICK: '§6[victim]§7 n''a pas réussi à éteindre le feu'
FLY_INTO_WALL: '§6[victim]§7 s''est mangé un mur'
HOT_FLOOR: '§6[victim]§7 a marché sur du sol brulant'
LAVA: '§6[victim]§7 est mort dans la lave'
LIGHTNING: '§6[victim]§7 s''est pris la foudre'
MAGIC: '§6[victim]§7 est victime d''une mort magique'
MELTING: '§6[victim]§7 à fondu'
POISON: '§6[victim]§7 est mort empoisoné'
PROJECTILE: '§6[victim]§7 s''est fais tiré dessus'
STRAVATION: '§6[victim]§7 est mort de faim'
SUFFOCATION: '§6[victim]§7 à suffoqué dans un mur'
SUICIDE: '§6[victim]§7 s''est suicidé'
THORNS: '§6[victim]§7 à été piqué'
VOID: '§6[victim]§7 est mort dans le vide'
WITHER: '§6[victim]§7 à été tué par un Wither'

# plugin's custom death message
ARROW: '§6[victim]§7 s''est fais tiré dessus'

# death messages' complements
by_message: ' par §6[killer]'
in_message: ' dans §8[killer]'
using_message: ' §7avec §8[using]'
escaping_message: ' pour tenter d''échapper à §6[killer]'

death_counter_message: '§6[victim]§7 est à §8[deaths]§7 morts'